// AI tools data — prices in USD/month, free tokens describe daily renewal where applicable
window.AI_TOOLS = [
  // ---------- LLM / Chat ----------
  {
    id: "chatgpt",
    name: "ChatGPT",
    vendor: "OpenAI",
    monogram: "CG",
    monoColor: "#10a37f",
    category: "llm",
    description: "Универсальный чат-ассистент с голосом, поиском и кодом.",
    basicPrice: 20,
    basicLabel: "Plus",
    proPrice: 200,
    proLabel: "Pro",
    freeTier: true,
    freeDaily: true,
    freeNote: "Лимиты GPT-5 mini ежедневно",
    tags: ["llm", "image", "audio", "search"],
  },
  {
    id: "claude",
    name: "Claude",
    vendor: "Anthropic",
    monogram: "Cl",
    monoColor: "#cc785c",
    category: "llm",
    description: "Длинный контекст, проекты, артефакты и Computer Use.",
    basicPrice: 20,
    basicLabel: "Pro",
    proPrice: 200,
    proLabel: "Max",
    freeTier: true,
    freeDaily: true,
    freeNote: "Sonnet с ежедневной квотой",
    tags: ["llm", "code"],
  },
  {
    id: "gemini",
    name: "Gemini",
    vendor: "Google",
    monogram: "Ge",
    monoColor: "#4285f4",
    category: "llm",
    description: "Мультимодальный ассистент с интеграцией Google Workspace.",
    basicPrice: 20,
    basicLabel: "AI Pro",
    proPrice: 250,
    proLabel: "AI Ultra",
    freeTier: true,
    freeDaily: true,
    freeNote: "2.5 Flash без лимита по дню",
    tags: ["llm", "image", "video", "audio"],
  },
  {
    id: "grok",
    name: "Grok",
    vendor: "xAI",
    monogram: "Gk",
    monoColor: "#1d1d1d",
    category: "llm",
    description: "Модель с доступом к ленте X и режимом DeepSearch.",
    basicPrice: 30,
    basicLabel: "SuperGrok",
    proPrice: 300,
    proLabel: "Heavy",
    freeTier: true,
    freeDaily: true,
    freeNote: "До 20 запросов / 2ч",
    tags: ["llm", "image", "search"],
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    vendor: "DeepSeek",
    monogram: "DS",
    monoColor: "#4d6bfe",
    category: "llm",
    description: "Открытая reasoning-модель с дешёвым API и веб-чатом.",
    basicPrice: 0,
    basicLabel: "Free",
    proPrice: 0,
    proLabel: "API pay-as-you-go",
    freeTier: true,
    freeDaily: true,
    freeNote: "Веб-чат без лимита",
    tags: ["llm", "code"],
  },
  {
    id: "mistral",
    name: "Le Chat",
    vendor: "Mistral",
    monogram: "Mi",
    monoColor: "#fa520f",
    category: "llm",
    description: "Французский ассистент с агентами и Canvas.",
    basicPrice: 15,
    basicLabel: "Pro",
    proPrice: 50,
    proLabel: "Team",
    freeTier: true,
    freeDaily: true,
    freeNote: "Базовая модель без лимита",
    tags: ["llm", "code", "search"],
  },

  // ---------- Image ----------
  {
    id: "midjourney",
    name: "Midjourney",
    vendor: "Midjourney",
    monogram: "Mj",
    monoColor: "#1f1f1f",
    category: "image",
    description: "Художественный генератор изображений с собственной эстетикой.",
    basicPrice: 10,
    basicLabel: "Basic",
    proPrice: 120,
    proLabel: "Mega",
    freeTier: false,
    freeDaily: false,
    freeNote: null,
    tags: ["image", "video"],
  },
  {
    id: "ideogram",
    name: "Ideogram",
    vendor: "Ideogram",
    monogram: "Id",
    monoColor: "#ff4f00",
    category: "image",
    description: "Генератор с реалистичным текстом на картинке и типографикой.",
    basicPrice: 8,
    basicLabel: "Basic",
    proPrice: 60,
    proLabel: "Pro",
    freeTier: true,
    freeDaily: true,
    freeNote: "10 быстрых генераций / день",
    tags: ["image"],
  },
  {
    id: "flux",
    name: "Flux",
    vendor: "Black Forest Labs",
    monogram: "Fl",
    monoColor: "#000000",
    category: "image",
    description: "Семейство open-weight моделей с фотореалистичной детализацией.",
    basicPrice: 0,
    basicLabel: "API",
    proPrice: 0,
    proLabel: "Self-host",
    freeTier: false,
    freeDaily: false,
    freeNote: null,
    tags: ["image"],
  },
  {
    id: "krea",
    name: "Krea",
    vendor: "Krea",
    monogram: "Kr",
    monoColor: "#0066ff",
    category: "image",
    description: "Реалтайм-канвас для генерации, апскейла и видео.",
    basicPrice: 12,
    basicLabel: "Basic",
    proPrice: 60,
    proLabel: "Max",
    freeTier: true,
    freeDaily: true,
    freeNote: "Ограниченные кредиты ежедневно",
    tags: ["image", "video"],
  },
  {
    id: "recraft",
    name: "Recraft",
    vendor: "Recraft",
    monogram: "Rc",
    monoColor: "#ff5b3a",
    category: "image",
    description: "Векторная и брендированная графика с управлением стилем.",
    basicPrice: 12,
    basicLabel: "Basic",
    proPrice: 60,
    proLabel: "Pro",
    freeTier: true,
    freeDaily: true,
    freeNote: "50 кредитов / день",
    tags: ["image"],
  },

  // ---------- Video ----------
  {
    id: "runway",
    name: "Runway",
    vendor: "Runway",
    monogram: "Rw",
    monoColor: "#0c0c0c",
    category: "video",
    description: "Видеогенерация Gen-4 с управлением камерой и инпеинтингом.",
    basicPrice: 15,
    basicLabel: "Standard",
    proPrice: 95,
    proLabel: "Unlimited",
    freeTier: true,
    freeDaily: false,
    freeNote: "125 кредитов разово",
    tags: ["video", "image"],
  },
  {
    id: "sora",
    name: "Sora",
    vendor: "OpenAI",
    monogram: "So",
    monoColor: "#000000",
    category: "video",
    description: "Текст-в-видео внутри подписки ChatGPT Plus и Pro.",
    basicPrice: 20,
    basicLabel: "Plus",
    proPrice: 200,
    proLabel: "Pro",
    freeTier: false,
    freeDaily: false,
    freeNote: null,
    tags: ["video"],
  },
  {
    id: "veo",
    name: "Veo",
    vendor: "Google DeepMind",
    monogram: "Ve",
    monoColor: "#1a73e8",
    category: "video",
    description: "Высокое разрешение и долгие сцены в Flow и Gemini.",
    basicPrice: 20,
    basicLabel: "AI Pro",
    proPrice: 250,
    proLabel: "AI Ultra",
    freeTier: false,
    freeDaily: false,
    freeNote: null,
    tags: ["video"],
  },
  {
    id: "pika",
    name: "Pika",
    vendor: "Pika Labs",
    monogram: "Pk",
    monoColor: "#ff2d6f",
    category: "video",
    description: "Короткие клипы с эффектами «Pikaffects» и липсинком.",
    basicPrice: 10,
    basicLabel: "Standard",
    proPrice: 95,
    proLabel: "Fancy",
    freeTier: true,
    freeDaily: false,
    freeNote: "80 кредитов на старт",
    tags: ["video"],
  },
  {
    id: "luma",
    name: "Luma Dream Machine",
    vendor: "Luma AI",
    monogram: "Lu",
    monoColor: "#1a1a1a",
    category: "video",
    description: "Кинематографичное видео с управлением кадром Ray-2.",
    basicPrice: 10,
    basicLabel: "Lite",
    proPrice: 95,
    proLabel: "Premier",
    freeTier: true,
    freeDaily: true,
    freeNote: "30 генераций / день",
    tags: ["video", "image"],
  },
  {
    id: "heygen",
    name: "HeyGen",
    vendor: "HeyGen",
    monogram: "Hg",
    monoColor: "#5046e5",
    category: "video",
    description: "Цифровые аватары с дубляжом и липсинком на 175 языках.",
    basicPrice: 29,
    basicLabel: "Creator",
    proPrice: 330,
    proLabel: "Scale",
    freeTier: true,
    freeDaily: false,
    freeNote: "3 видео на бесплатном тарифе",
    tags: ["video", "audio"],
  },

  // ---------- Audio ----------
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    vendor: "ElevenLabs",
    monogram: "El",
    monoColor: "#0b0b0b",
    category: "audio",
    description: "Реалистичный TTS, клонирование голоса и дубляж.",
    basicPrice: 5,
    basicLabel: "Starter",
    proPrice: 330,
    proLabel: "Business",
    freeTier: true,
    freeDaily: false,
    freeNote: "10 000 знаков / мес",
    tags: ["audio"],
  },
  {
    id: "suno",
    name: "Suno",
    vendor: "Suno",
    monogram: "Su",
    monoColor: "#111111",
    category: "audio",
    description: "Генерация полноценных песен с вокалом по промпту.",
    basicPrice: 10,
    basicLabel: "Pro",
    proPrice: 30,
    proLabel: "Premier",
    freeTier: true,
    freeDaily: true,
    freeNote: "50 кредитов / день",
    tags: ["audio"],
  },
  {
    id: "udio",
    name: "Udio",
    vendor: "Udio",
    monogram: "Ud",
    monoColor: "#7a3cff",
    category: "audio",
    description: "Музыкальный генератор с акцентом на качество вокала.",
    basicPrice: 10,
    basicLabel: "Standard",
    proPrice: 30,
    proLabel: "Pro",
    freeTier: true,
    freeDaily: true,
    freeNote: "10 треков / день",
    tags: ["audio"],
  },
  {
    id: "descript",
    name: "Descript",
    vendor: "Descript",
    monogram: "De",
    monoColor: "#16c8c8",
    category: "audio",
    description: "Редактор аудио и видео по тексту с Overdub-голосами.",
    basicPrice: 16,
    basicLabel: "Hobbyist",
    proPrice: 50,
    proLabel: "Business",
    freeTier: true,
    freeDaily: false,
    freeNote: "1 час транскрипции / мес",
    tags: ["audio", "video"],
  },

  // ---------- Code ----------
  {
    id: "cursor",
    name: "Cursor",
    vendor: "Anysphere",
    monogram: "Cu",
    monoColor: "#0b0b0b",
    category: "code",
    description: "IDE на базе VS Code с агентом для рефакторинга всего репозитория.",
    basicPrice: 20,
    basicLabel: "Pro",
    proPrice: 200,
    proLabel: "Ultra",
    freeTier: true,
    freeDaily: false,
    freeNote: "2 недели Pro триал",
    tags: ["code", "llm"],
  },
  {
    id: "copilot",
    name: "GitHub Copilot",
    vendor: "GitHub",
    monogram: "Co",
    monoColor: "#1f1f1f",
    category: "code",
    description: "Inline-подсказки и чат внутри IDE с переключаемыми моделями.",
    basicPrice: 10,
    basicLabel: "Pro",
    proPrice: 39,
    proLabel: "Enterprise",
    freeTier: true,
    freeDaily: false,
    freeNote: "2000 автодополнений / мес",
    tags: ["code"],
  },
  {
    id: "v0",
    name: "v0",
    vendor: "Vercel",
    monogram: "v0",
    monoColor: "#000000",
    category: "code",
    description: "Генерация React-компонентов и страниц по промпту.",
    basicPrice: 20,
    basicLabel: "Premium",
    proPrice: 200,
    proLabel: "Ultra",
    freeTier: true,
    freeDaily: true,
    freeNote: "Дневные кредиты на бесплатке",
    tags: ["code", "llm"],
  },
  {
    id: "lovable",
    name: "Lovable",
    vendor: "Lovable",
    monogram: "Lv",
    monoColor: "#ff5470",
    category: "code",
    description: "Полноценные веб-приложения из чата с деплоем в один клик.",
    basicPrice: 25,
    basicLabel: "Pro",
    proPrice: 100,
    proLabel: "Scale",
    freeTier: true,
    freeDaily: true,
    freeNote: "5 сообщений / день",
    tags: ["code"],
  },
  {
    id: "windsurf",
    name: "Windsurf",
    vendor: "Codeium",
    monogram: "Ws",
    monoColor: "#09b6a2",
    category: "code",
    description: "Агентный редактор с потоками Cascade для длинных задач.",
    basicPrice: 15,
    basicLabel: "Pro",
    proPrice: 60,
    proLabel: "Teams",
    freeTier: true,
    freeDaily: false,
    freeNote: "25 prompt-кредитов / мес",
    tags: ["code"],
  },

  // ---------- Search / Research ----------
  {
    id: "perplexity",
    name: "Perplexity",
    vendor: "Perplexity",
    monogram: "Px",
    monoColor: "#20808d",
    category: "research",
    description: "Поисковый ассистент с цитатами и режимом глубокого исследования.",
    basicPrice: 20,
    basicLabel: "Pro",
    proPrice: 200,
    proLabel: "Max",
    freeTier: true,
    freeDaily: true,
    freeNote: "3 Pro-поиска / день",
    tags: ["search", "llm"],
  },
  {
    id: "you",
    name: "You.com",
    vendor: "You",
    monogram: "Yo",
    monoColor: "#9747ff",
    category: "research",
    description: "Мультиагентный поиск с переключаемыми режимами Research.",
    basicPrice: 15,
    basicLabel: "Pro",
    proPrice: 50,
    proLabel: "Team",
    freeTier: true,
    freeDaily: true,
    freeNote: "Базовый поиск без лимита",
    tags: ["search", "llm"],
  },
  {
    id: "elicit",
    name: "Elicit",
    vendor: "Elicit",
    monogram: "Ec",
    monoColor: "#1a1a1a",
    category: "research",
    description: "Анализ научных статей и извлечение данных из PDF.",
    basicPrice: 12,
    basicLabel: "Plus",
    proPrice: 49,
    proLabel: "Pro",
    freeTier: true,
    freeDaily: false,
    freeNote: "5000 кредитов разово",
    tags: ["search"],
  },

  // ---------- Aggregators ----------
  {
    id: "openrouter",
    name: "OpenRouter",
    vendor: "OpenRouter",
    monogram: "OR",
    monoColor: "#6366f1",
    category: "aggregator",
    description: "Единый API и чат для 400+ моделей с прозрачной ценой за токены.",
    basicPrice: 0,
    basicLabel: "Pay-as-you-go",
    proPrice: 0,
    proLabel: "Enterprise",
    freeTier: true,
    freeDaily: true,
    freeNote: "Бесплатные модели без лимита",
    models: 421,
    tags: ["llm", "image", "code"],
  },
  {
    id: "poe",
    name: "Poe",
    vendor: "Quora",
    monogram: "Po",
    monoColor: "#5d3bee",
    category: "aggregator",
    description: "Подписка на единую балансную систему ботов разных моделей.",
    basicPrice: 20,
    basicLabel: "Premium",
    proPrice: 250,
    proLabel: "Enterprise",
    freeTier: true,
    freeDaily: true,
    freeNote: "150 points / день",
    models: 120,
    tags: ["llm", "image", "video", "audio"],
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    vendor: "Hugging Face",
    monogram: "HF",
    monoColor: "#ffcc4d",
    category: "aggregator",
    description: "Хаб open-source моделей с inference endpoints и Spaces.",
    basicPrice: 9,
    basicLabel: "Pro",
    proPrice: 20,
    proLabel: "Team",
    freeTier: true,
    freeDaily: true,
    freeNote: "Serverless лимит ежедневно",
    models: 1500000,
    tags: ["llm", "image", "audio", "video", "code"],
  },
  {
    id: "replicate",
    name: "Replicate",
    vendor: "Replicate",
    monogram: "Rp",
    monoColor: "#0b0b0b",
    category: "aggregator",
    description: "Хостинг и запуск open-source моделей через API по секундам.",
    basicPrice: 0,
    basicLabel: "Pay-as-you-go",
    proPrice: 0,
    proLabel: "Enterprise",
    freeTier: true,
    freeDaily: false,
    freeNote: "$5 разовый кредит",
    models: 50000,
    tags: ["llm", "image", "video", "audio"],
  },
  {
    id: "fal",
    name: "fal",
    vendor: "fal.ai",
    monogram: "fa",
    monoColor: "#ff3d8b",
    category: "aggregator",
    description: "Реалтайм-инференс генеративных моделей с фокусом на скорость.",
    basicPrice: 0,
    basicLabel: "Pay-as-you-go",
    proPrice: 0,
    proLabel: "Enterprise",
    freeTier: true,
    freeDaily: false,
    freeNote: "$1 на старте",
    models: 600,
    tags: ["image", "video", "audio"],
  },
];

window.AI_CATEGORIES = [
  { id: "all",        label: "Все",          hint: "вся таблица" },
  { id: "llm",        label: "LLM / Чат",    hint: "текст и рассуждения" },
  { id: "image",      label: "Картинки",     hint: "генерация изображений" },
  { id: "video",      label: "Видео",        hint: "text-to-video" },
  { id: "audio",      label: "Аудио",        hint: "TTS и музыка" },
  { id: "code",       label: "Код",          hint: "IDE и копилоты" },
  { id: "research",   label: "Ресёрч",       hint: "поиск с цитатами" },
  { id: "aggregator", label: "Агрегаторы",   hint: "доступ ко многим моделям" },
];

window.AI_TAG_LABELS = {
  llm:    "LLM",
  image:  "Картинки",
  video:  "Видео",
  audio:  "Аудио",
  code:   "Код",
  search: "Поиск",
};
